services:
  titan_ea_demo:
    container_name: titan_ea_demo
    # Prebuilt sometimes :-)
    # image: jgruberf5/titan_ea_demo:latest
    build: .
    ports:
      - 8100:8100
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - API_LISTENER_ADDRESS=0.0.0.0
      - API_LISTENER_PORT=8100
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    depends_on:
      - chromadb
      - ollama
  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    ports:
      - 8000:8000
    volumes:
      - ./data/chroma:/chroma/chroma
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    tty: true
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama